### ISSUE TITLE
Plugin doesn't sorts original select option

### ISSUE THREAD

**Issue by matteopoile** [vafour/select2-sortable#1]
Plugin doesn't sorts original select option.
I can sort visually the lis inside .select2-container but the order of the option in the original select doesn't change thus the order of the values submitted by the form doesn't change.
I'm having this problem but I'm not sure the plugin is made to sort the original select options too.

**Comment by ayublin** [comment]
Hi, the plugin does the actual sorting to the select options, but not in the real time manner. If you observe [this part](https://github.com/vafour/select2-sortable/blob/90104cb30cb04e417fca35dc29627a542024ba1f/select2.sortable.js#L47-L54) of codes, you will notice that the actual sorting is done when the closest form to the select is submitted, if the value submitted doesn't change there maybe some situation in your codes that make the plugin miss the submit event, could you confirm on this?

I understand that form submit event may not be the best time to do the actual sorting, a better option maybe is to do the actual sorting at jQuery sortable `stop` event callback, I can try to implement this if you also think this is better.

Thanks!

**Comment by matteopoile** [comment]
Ok, now I understood.
Sorting on submit is the right choice in almost all cases.
In my case the form is submitted via ajax and the default submit event is prevented using jQuery  event.preventDefault();
Sorting on jQuery sortable stop will make the very difference in my case.
Maybe you could also give the possibility to sort programmatically.

I just tried something like $('myselectid').select2().select2Order() via Firebug console before send the ajax request but nothing happened.

**Comment by matteopoile** [comment]
Another upgrade will be allow something like:
$('myselectid').select2();
$('myselectid').select2Sortable();
$('myselectid').select2Sortable('destroy');

This is a very little thing but helps in case you will make sortable or not an existent select2 object based on a click or variable evaluation.

Maybe I'm wrong but it seems now it works only directly after .select2().
Do you think this will be possible?

**Comment by ayublin** [comment]
:+1: Those are legit ideas and should not be hard to implement, we can call `select2()` upon `select2Sortable` initialization anyway since if the element is already `select2`-ed nothing will happens, I will try to implement them soon.

**Comment by matteopoile** [comment]
Thank you very much!
You are very kind

**Comment by ayublin** [comment]
You're welcome! now you can call

```
// init select2 sortable
$('myselectid').select2Sortable();

// destroy select2 sortable
$('myselectid').select2Sortable('destroy');

// select2 sortable options ordering
$('myselectid').select2SortableOrder();
```

Let me know if you encountered a bug.

**Comment by matteopoile** [comment]
Thanks ayublin for your very quick commit. 
I'm testing the new code and I found some problems.
I'm not skilled as you in js/jQuery but I'm trying to patch it to lighten your work hoping a chunk of my code could be a good starting point for your further optimizations.

**Comment by ayublin** [comment]
No problem matteo, I am far from skilled and obviously I am learning from you in this matter :) And I would really appreciate that chunk of code :icecream: (Oh, I just discovered those cute emoticons)
