### ISSUE TITLE
Help with Form Submit

### ISSUE THREAD

**Issue by dovy** [vafour/select2-sortable#8]
So I've looked at your help docs. I've fixed my CSS issue. I still, however, can't get the order to save on a form submit.

Can you give me a bit more guidance than was in Issue #1?

IE, it sorts, but I need reordering of the select to occur or all is for naught.

Thanks.

**Comment by ayublin** [comment]
Hi @dovy,

The select should be reordered upon form submit by default if `bindOrder` isn't set to `sortableStop`. It works by binding itself to the closest form submit event:

https://github.com/vafour/select2-sortable/blob/master/select2.sortable.js#L87-L89

Do you think that may cause an issue in your case?

**Comment by dovy** [comment]
It reorders visually, but not by markup. I've even added a on change function to run `$(this).select2SortableOrder()` without any success.

My select2 is bound to an options list. Is that going to be a problem?

**Comment by ayublin** [comment]
Yes, the markup reordering is fired up upon:
1. `formSubmit`: Submit event of the closest `form` element by the select2sortable element.
2. `sortableStop`: Ordering fired in jQuery UI `sortableStop` event, so the markup will be re-ordered in real time manner every time the users sorting an item.

Please try using the `sortableStop` option:

```
$(select2multiselect).select2Sortable({
    bindOrder: `sortableStop`
});
```

So you don't have to bind and fire `select2SortableOrder` manually.

I stumbled upon Redux Framework several times, and saw you as one of the rocking contributors, so I just take a peek on your code for the select field :)

https://github.com/ReduxFramework/ReduxFramework/blob/master/ReduxCore/inc/fields/select/field_select.js#L31

Referring to that line, there is a mistake on defining the `bindOrder`, as I stated above, it should be `formSubmit` or `sortableStop`, you can refer to the readme:

https://github.com/vafour/select2-sortable/blob/master/README.md

Please try changing that line and see if the reordering fired properly :)

**Comment by dovy** [comment]
Previously tried that to no avail. Just tried again, no change.

Thanks for the kind words. Redux is my baby.

I think something must be wrong with how I set the select2 perhaps.  :(

**Comment by ayublin** [comment]
Hmm that's weird, do you have a link for Redux sample theme with the latest github repo version of Redux? Maybe I can install and try something out on my end. Thanks before!

**Comment by dovy** [comment]
https://github.com/ReduxFramework/ReduxFramework/archive/master.zip

Install as a Wordpress plugin.

Once installed, go to the plugins page in the wp-admin and find ReduxFramework. Click on Activate demo mode.

Click on the new `Options` sidebar that appears and go to the Select Fields tab.

Find a multi-select. Fill with data. You'll find that you can sort anything, but the saving doesn't work. Or rather, saving the order doesn't work.

**Comment by ayublin** [comment]
Hi @dovy,

I just tried it out, and the markup does reordered, to test this, try removing the `select2-offscreen` class at the select element. Then try doing sorting, and you should see that the original options are being sorted.

So I guess there is something needed to be done in order to persist the ordering in the database :)

**Comment by dovy** [comment]
You were totally right. Thanks for taking the time.

My last questions pertains to autocomplete. There's a hidden autocomplete list item which the sortable makes a space for at the end of the sortable area. Any way to hide that field perhaps?

**Comment by dovy** [comment]
And nevermind, a display done made it all better.

Bless you for this great plugin. The "select2" standard method is horrible.

**Comment by ayublin** [comment]
Cool, glad to know you got the issue sorted ! And yes, exactly why we build this little plugin :)
